/**
 * Accounting module: chart of accounts (master) + transactions filtered by date.
 * Transaction tables are extracted only for records dated >= TRANSACTION_DATE_FROM.
 */

import type { OdooModule } from "../types";

export const accountingModule: OdooModule = {
  name: "accounting",
  label: "Accounting",
  description: "Chart of accounts, journals, taxes, and accounting transactions",
  tables: [
    // ===== Master data =====
    {
      tableName: "account_account",
      odooModel: "account.account",
      label: "Chart of Accounts",
      type: "master",
      importOrder: 100,
    },
    {
      tableName: "account_journal",
      odooModel: "account.journal",
      label: "Journals",
      type: "master",
      importOrder: 110,
    },
    {
      tableName: "account_tax",
      odooModel: "account.tax",
      label: "Taxes",
      type: "master",
      importOrder: 120,
    },
    {
      tableName: "account_tax_group",
      odooModel: "account.tax.group",
      label: "Tax Groups",
      type: "master",
      importOrder: 119,
    },
    {
      tableName: "account_fiscal_position",
      odooModel: "account.fiscal.position",
      label: "Fiscal Positions",
      type: "master",
      importOrder: 130,
    },
    {
      tableName: "account_payment_term",
      odooModel: "account.payment.term",
      label: "Payment Terms",
      type: "master",
      importOrder: 140,
    },
    // ===== Transactions (date filtered) =====
    {
      tableName: "account_move",
      odooModel: "account.move",
      label: "Journal Entries / Invoices / Bills",
      type: "transaction",
      dateFilterColumn: "date",
      importOrder: 500,
    },
    {
      tableName: "account_move_line",
      odooModel: "account.move.line",
      label: "Journal Items",
      type: "transaction",
      dateFilterColumn: "date",
      importOrder: 510,
    },
    {
      tableName: "account_payment",
      odooModel: "account.payment",
      label: "Payments",
      type: "transaction",
      dateFilterColumn: "date",
      importOrder: 520,
    },
    {
      tableName: "sale_order",
      odooModel: "sale.order",
      label: "Sales Orders",
      type: "transaction",
      dateFilterColumn: "date_order",
      importOrder: 400,
    },
    {
      tableName: "sale_order_line",
      odooModel: "sale.order.line",
      label: "Sales Order Lines",
      type: "transaction",
      dateFilterColumn: "create_date",
      importOrder: 401,
    },
    {
      tableName: "purchase_order",
      odooModel: "purchase.order",
      label: "Purchase Orders",
      type: "transaction",
      dateFilterColumn: "date_order",
      importOrder: 410,
    },
    {
      tableName: "purchase_order_line",
      odooModel: "purchase.order.line",
      label: "Purchase Order Lines",
      type: "transaction",
      dateFilterColumn: "create_date",
      importOrder: 411,
    },
    {
      tableName: "stock_picking",
      odooModel: "stock.picking",
      label: "Stock Pickings",
      type: "transaction",
      dateFilterColumn: "scheduled_date",
      importOrder: 420,
    },
    {
      tableName: "stock_move",
      odooModel: "stock.move",
      label: "Stock Moves",
      type: "transaction",
      dateFilterColumn: "date",
      importOrder: 421,
    },
    {
      tableName: "stock_move_line",
      odooModel: "stock.move.line",
      label: "Stock Move Lines",
      type: "transaction",
      dateFilterColumn: "date",
      importOrder: 422,
    },
    {
      tableName: "stock_valuation_layer",
      odooModel: "stock.valuation.layer",
      label: "Inventory Valuation Layers",
      type: "transaction",
      dateFilterColumn: "create_date",
      importOrder: 430,
    },
  ],
  relations: [
    {
      fromTable: "account_move",
      fromColumn: "partner_id",
      toTable: "res_partner",
      toColumn: "id",
      onDelete: "block",
      label: "Invoice partner",
    },
    {
      fromTable: "account_move",
      fromColumn: "journal_id",
      toTable: "account_journal",
      toColumn: "id",
      onDelete: "block",
      label: "Invoice journal",
    },
    {
      fromTable: "account_move",
      fromColumn: "currency_id",
      toTable: "res_currency",
      toColumn: "id",
      onDelete: "block",
      label: "Invoice currency",
    },
    {
      fromTable: "account_move",
      fromColumn: "company_id",
      toTable: "res_company",
      toColumn: "id",
      onDelete: "block",
      label: "Invoice company",
    },
    {
      fromTable: "account_move_line",
      fromColumn: "move_id",
      toTable: "account_move",
      toColumn: "id",
      onDelete: "cascade",
      label: "Parent journal entry",
    },
    {
      fromTable: "account_move_line",
      fromColumn: "account_id",
      toTable: "account_account",
      toColumn: "id",
      onDelete: "block",
      label: "Line account",
    },
    {
      fromTable: "account_move_line",
      fromColumn: "partner_id",
      toTable: "res_partner",
      toColumn: "id",
      onDelete: "nullify",
      label: "Line partner",
    },
    {
      fromTable: "account_journal",
      fromColumn: "default_account_id",
      toTable: "account_account",
      toColumn: "id",
      onDelete: "nullify",
      label: "Journal default account",
    },
    {
      fromTable: "account_journal",
      fromColumn: "company_id",
      toTable: "res_company",
      toColumn: "id",
      onDelete: "block",
      label: "Journal company",
    },
    {
      fromTable: "sale_order",
      fromColumn: "partner_id",
      toTable: "res_partner",
      toColumn: "id",
      onDelete: "block",
      label: "Sale order customer",
    },
    {
      fromTable: "sale_order_line",
      fromColumn: "order_id",
      toTable: "sale_order",
      toColumn: "id",
      onDelete: "cascade",
      label: "Parent sale order",
    },
    {
      fromTable: "sale_order_line",
      fromColumn: "product_id",
      toTable: "product_product",
      toColumn: "id",
      onDelete: "block",
      label: "SO line product",
    },
    {
      fromTable: "purchase_order",
      fromColumn: "partner_id",
      toTable: "res_partner",
      toColumn: "id",
      onDelete: "block",
      label: "Purchase order vendor",
    },
    {
      fromTable: "purchase_order_line",
      fromColumn: "order_id",
      toTable: "purchase_order",
      toColumn: "id",
      onDelete: "cascade",
      label: "Parent purchase order",
    },
    {
      fromTable: "purchase_order_line",
      fromColumn: "product_id",
      toTable: "product_product",
      toColumn: "id",
      onDelete: "block",
      label: "PO line product",
    },
    {
      fromTable: "stock_move",
      fromColumn: "picking_id",
      toTable: "stock_picking",
      toColumn: "id",
      onDelete: "cascade",
      label: "Parent picking",
    },
    {
      fromTable: "stock_move",
      fromColumn: "product_id",
      toTable: "product_product",
      toColumn: "id",
      onDelete: "block",
      label: "Stock move product",
    },
    {
      fromTable: "stock_move",
      fromColumn: "location_id",
      toTable: "stock_location",
      toColumn: "id",
      onDelete: "block",
      label: "Source location",
    },
    {
      fromTable: "stock_move",
      fromColumn: "location_dest_id",
      toTable: "stock_location",
      toColumn: "id",
      onDelete: "block",
      label: "Destination location",
    },
  ],
};
