/**
 * Base module: core master data tables.
 * All records are extracted, including archived (active = false).
 */

import type { OdooModule } from "../types";

export const baseModule: OdooModule = {
  name: "base",
  label: "Base & Master Data",
  description: "Core master data: partners, companies, products, users, currencies",
  tables: [
    {
      tableName: "res_company",
      odooModel: "res.company",
      label: "Companies",
      type: "master",
      importOrder: 10,
    },
    {
      tableName: "res_currency",
      odooModel: "res.currency",
      label: "Currencies",
      type: "master",
      importOrder: 20,
    },
    {
      tableName: "res_country",
      odooModel: "res.country",
      label: "Countries",
      type: "master",
      importOrder: 25,
    },
    {
      tableName: "res_partner",
      odooModel: "res.partner",
      label: "Partners (Customers, Vendors, Contacts)",
      type: "master",
      importOrder: 30,
    },
    {
      tableName: "res_users",
      odooModel: "res.users",
      label: "Users",
      type: "master",
      importOrder: 40,
    },
    {
      tableName: "res_groups",
      odooModel: "res.groups",
      label: "User Groups",
      type: "master",
      importOrder: 45,
    },
    {
      tableName: "uom_uom",
      odooModel: "uom.uom",
      label: "Units of Measure",
      type: "master",
      importOrder: 50,
    },
    {
      tableName: "uom_category",
      odooModel: "uom.category",
      label: "Unit of Measure Categories",
      type: "master",
      importOrder: 49,
    },
    {
      tableName: "product_category",
      odooModel: "product.category",
      label: "Product Categories",
      type: "master",
      importOrder: 60,
    },
    {
      tableName: "product_template",
      odooModel: "product.template",
      label: "Product Templates",
      type: "master",
      importOrder: 70,
    },
    {
      tableName: "product_product",
      odooModel: "product.product",
      label: "Product Variants",
      type: "master",
      importOrder: 71,
    },
    {
      tableName: "hr_employee",
      odooModel: "hr.employee",
      label: "Employees",
      type: "master",
      importOrder: 80,
    },
    {
      tableName: "stock_warehouse",
      odooModel: "stock.warehouse",
      label: "Warehouses",
      type: "master",
      importOrder: 85,
    },
    {
      tableName: "stock_location",
      odooModel: "stock.location",
      label: "Stock Locations",
      type: "master",
      importOrder: 86,
    },
  ],
  relations: [
    {
      fromTable: "res_partner",
      fromColumn: "company_id",
      toTable: "res_company",
      toColumn: "id",
      onDelete: "nullify",
      label: "Partner's company",
    },
    {
      fromTable: "res_partner",
      fromColumn: "country_id",
      toTable: "res_country",
      toColumn: "id",
      onDelete: "nullify",
      label: "Partner's country",
    },
    {
      fromTable: "res_partner",
      fromColumn: "parent_id",
      toTable: "res_partner",
      toColumn: "id",
      onDelete: "nullify",
      label: "Parent partner",
    },
    {
      fromTable: "product_product",
      fromColumn: "product_tmpl_id",
      toTable: "product_template",
      toColumn: "id",
      onDelete: "block",
      label: "Product template",
    },
    {
      fromTable: "product_template",
      fromColumn: "categ_id",
      toTable: "product_category",
      toColumn: "id",
      onDelete: "block",
      label: "Product category",
    },
    {
      fromTable: "product_template",
      fromColumn: "uom_id",
      toTable: "uom_uom",
      toColumn: "id",
      onDelete: "block",
      label: "Product UoM",
    },
    {
      fromTable: "uom_uom",
      fromColumn: "category_id",
      toTable: "uom_category",
      toColumn: "id",
      onDelete: "block",
      label: "UoM category",
    },
    {
      fromTable: "stock_warehouse",
      fromColumn: "company_id",
      toTable: "res_company",
      toColumn: "id",
      onDelete: "block",
      label: "Warehouse company",
    },
    {
      fromTable: "stock_location",
      fromColumn: "company_id",
      toTable: "res_company",
      toColumn: "id",
      onDelete: "nullify",
      label: "Location company",
    },
  ],
};
