/**
 * Manufacturing module: work centers, BoMs and manufacturing orders.
 */

import type { OdooModule } from "../types";

export const mrpModule: OdooModule = {
  name: "mrp",
  label: "Manufacturing",
  description: "Work centers, bills of materials and manufacturing orders",
  tables: [
    // ===== Master data =====
    {
      tableName: "mrp_workcenter",
      odooModel: "mrp.workcenter",
      label: "Work Centers",
      type: "master",
      importOrder: 450,
    },
    {
      tableName: "mrp_routing_workcenter",
      odooModel: "mrp.routing.workcenter",
      label: "Operations",
      type: "master",
      importOrder: 460,
    },
    {
      tableName: "mrp_bom",
      odooModel: "mrp.bom",
      label: "Bills of Materials",
      type: "master",
      importOrder: 470,
    },
    {
      tableName: "mrp_bom_line",
      odooModel: "mrp.bom.line",
      label: "BoM Components",
      type: "master",
      importOrder: 471,
    },
    // ===== Transactions =====
    {
      tableName: "mrp_production",
      odooModel: "mrp.production",
      label: "Manufacturing Orders",
      type: "transaction",
      dateFilterColumn: "date_planned_start",
      importOrder: 480,
    },
    {
      tableName: "mrp_workorder",
      odooModel: "mrp.workorder",
      label: "Work Orders",
      type: "transaction",
      dateFilterColumn: "date_planned_start",
      importOrder: 481,
    },
  ],
  relations: [
    {
      fromTable: "mrp_workcenter",
      fromColumn: "company_id",
      toTable: "res_company",
      toColumn: "id",
      onDelete: "block",
      label: "Work center company",
    },
    {
      fromTable: "mrp_routing_workcenter",
      fromColumn: "workcenter_id",
      toTable: "mrp_workcenter",
      toColumn: "id",
      onDelete: "block",
      label: "Operation work center",
    },
    {
      fromTable: "mrp_routing_workcenter",
      fromColumn: "bom_id",
      toTable: "mrp_bom",
      toColumn: "id",
      onDelete: "cascade",
      label: "Operation BoM",
    },
    {
      fromTable: "mrp_bom",
      fromColumn: "product_tmpl_id",
      toTable: "product_template",
      toColumn: "id",
      onDelete: "block",
      label: "BoM product template",
    },
    {
      fromTable: "mrp_bom",
      fromColumn: "product_id",
      toTable: "product_product",
      toColumn: "id",
      onDelete: "nullify",
      label: "BoM specific variant",
    },
    {
      fromTable: "mrp_bom",
      fromColumn: "product_uom_id",
      toTable: "uom_uom",
      toColumn: "id",
      onDelete: "block",
      label: "BoM unit of measure",
    },
    {
      fromTable: "mrp_bom",
      fromColumn: "company_id",
      toTable: "res_company",
      toColumn: "id",
      onDelete: "block",
      label: "BoM company",
    },
    {
      fromTable: "mrp_bom_line",
      fromColumn: "bom_id",
      toTable: "mrp_bom",
      toColumn: "id",
      onDelete: "cascade",
      label: "Parent BoM",
    },
    {
      fromTable: "mrp_bom_line",
      fromColumn: "product_id",
      toTable: "product_product",
      toColumn: "id",
      onDelete: "block",
      label: "Component product",
    },
    {
      fromTable: "mrp_bom_line",
      fromColumn: "product_uom_id",
      toTable: "uom_uom",
      toColumn: "id",
      onDelete: "block",
      label: "Component unit of measure",
    },
    {
      fromTable: "mrp_production",
      fromColumn: "product_id",
      toTable: "product_product",
      toColumn: "id",
      onDelete: "block",
      label: "MO product",
    },
    {
      fromTable: "mrp_production",
      fromColumn: "bom_id",
      toTable: "mrp_bom",
      toColumn: "id",
      onDelete: "nullify",
      label: "MO bill of materials",
    },
    {
      fromTable: "mrp_production",
      fromColumn: "product_uom_id",
      toTable: "uom_uom",
      toColumn: "id",
      onDelete: "block",
      label: "MO unit of measure",
    },
    {
      fromTable: "mrp_production",
      fromColumn: "location_src_id",
      toTable: "stock_location",
      toColumn: "id",
      onDelete: "block",
      label: "MO source location",
    },
    {
      fromTable: "mrp_production",
      fromColumn: "location_dest_id",
      toTable: "stock_location",
      toColumn: "id",
      onDelete: "block",
      label: "MO destination location",
    },
    {
      fromTable: "mrp_production",
      fromColumn: "picking_type_id",
      toTable: "stock_picking_type",
      toColumn: "id",
      onDelete: "block",
      label: "MO picking type",
    },
    {
      fromTable: "mrp_production",
      fromColumn: "company_id",
      toTable: "res_company",
      toColumn: "id",
      onDelete: "block",
      label: "MO company",
    },
    {
      fromTable: "mrp_workorder",
      fromColumn: "production_id",
      toTable: "mrp_production",
      toColumn: "id",
      onDelete: "cascade",
      label: "Parent manufacturing order",
    },
    {
      fromTable: "mrp_workorder",
      fromColumn: "workcenter_id",
      toTable: "mrp_workcenter",
      toColumn: "id",
      onDelete: "block",
      label: "Work order work center",
    },
    {
      fromTable: "mrp_workorder",
      fromColumn: "operation_id",
      toTable: "mrp_routing_workcenter",
      toColumn: "id",
      onDelete: "nullify",
      label: "Work order operation",
    },
  ],
};
